version: '3.9'

networks:
  app_network:
    name: app_network
    driver: bridge

services:
  nginx:
    container_name: nginx_app
    image: nginx:stable-alpine
    restart: always
    volumes:
        - .docker/default.conf:/etc/nginx/conf.d/default.conf
        - .:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app_network
  php:
    container_name: php_app
    build:
      context: .docker/
      dockerfile: php.dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    networks:
      - app_network
  db: 
    container_name: db_app
    image: postgres:17.3-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - .docker/local/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db
    networks:
      - app_network
